[package]
name = "uninstall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
build="build.rs"
[dependencies]
updateaddr={path="../updateaddr"}
send={path="../send"}
[build-dependencies]
cc = "1.0.78"
